// <auto-generated />
using System;
using ArmadaEsports.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Armada.Data.Migrations
{
    [DbContext(typeof(ArmadaDbContext))]
    [Migration("20260413174024_FixDecimalPrecision")]
    partial class FixDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArmadaEsports.Core.Models.AiMatchParseJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageMimeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RawOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("AiMatchParseJobs", (string)null);
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.AiParseJobRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AiConfidenceScore")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)");

                    b.Property<byte?>("Assists")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Goals")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Interceptions")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsManuallyEdited")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MatchRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("PassAccuracyPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("RawAlias")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte?>("Saves")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("ShotAccuracyPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<byte?>("Tackles")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("TacklesWon")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("PlayerId");

                    b.ToTable("AiParseJobRows", (string)null);
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompetitionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Competitions", (string)null);
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("GoalsAgainst")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("GoalsFor")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<short?>("Matchday")
                        .HasColumnType("smallint");

                    b.Property<string>("MatchdayLabel")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Result")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.MatchPerformanceStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AiConfidenceScore")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)");

                    b.Property<byte>("Assists")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Goals")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Interceptions")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsAiParsed")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MatchRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("PassAccuracyPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<byte>("Saves")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("ShotAccuracyPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<byte>("Tackles")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TacklesWon")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique();

                    b.ToTable("MatchPerformanceStats", (string)null);
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("JoinedAt")
                        .HasColumnType("date");

                    b.Property<int>("PrimaryPositionId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryPositionId")
                        .HasColumnType("int");

                    b.Property<int?>("TertiaryPositionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("JerseyNumber")
                        .IsUnique();

                    b.HasIndex("PrimaryPositionId");

                    b.HasIndex("SecondaryPositionId");

                    b.HasIndex("TertiaryPositionId");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.PlayerAttributeScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("AttributeIndex")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Score")
                        .HasColumnType("tinyint");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "AttributeIndex")
                        .IsUnique();

                    b.ToTable("PlayerAttributeScores", (string)null);
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.PlayerAttributeSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OverallRating")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("PlayerAttributeSnapshots", (string)null);
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PositionGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Positions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PO",
                            NameEs = "Portero",
                            PositionGroup = "Goalkeeper",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "DFD",
                            NameEs = "Defensa Central Derecho",
                            PositionGroup = "Defender",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "DFI",
                            NameEs = "Defensa Central Izquierdo",
                            PositionGroup = "Defender",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "LD",
                            NameEs = "Lateral Derecho",
                            PositionGroup = "Defender",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "LI",
                            NameEs = "Lateral Izquierdo",
                            PositionGroup = "Defender",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "MCD",
                            NameEs = "Mediocentro Defensivo",
                            PositionGroup = "Midfielder",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Code = "MVD",
                            NameEs = "Mediocentro Derecho",
                            PositionGroup = "Midfielder",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Code = "MI",
                            NameEs = "Extremo Izq / MVI",
                            PositionGroup = "Midfielder",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            Code = "MD",
                            NameEs = "Extremo Der / SDD",
                            PositionGroup = "Forward",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            Code = "DC",
                            NameEs = "Delantero Centro",
                            PositionGroup = "Forward",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            Code = "DCI",
                            NameEs = "Del. Centro Izq / SDI",
                            PositionGroup = "Forward",
                            SortOrder = 11
                        });
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.AiMatchParseJob", b =>
                {
                    b.HasOne("ArmadaEsports.Core.Models.Match", "Match")
                        .WithMany("ParseJobs")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.AiParseJobRow", b =>
                {
                    b.HasOne("ArmadaEsports.Core.Models.AiMatchParseJob", "Job")
                        .WithMany("Rows")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArmadaEsports.Core.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Job");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.Match", b =>
                {
                    b.HasOne("ArmadaEsports.Core.Models.Competition", "Competition")
                        .WithMany("Matches")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.MatchPerformanceStat", b =>
                {
                    b.HasOne("ArmadaEsports.Core.Models.Match", "Match")
                        .WithMany("PerformanceStats")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArmadaEsports.Core.Models.Player", "Player")
                        .WithMany("PerformanceStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.Player", b =>
                {
                    b.HasOne("ArmadaEsports.Core.Models.Position", "PrimaryPosition")
                        .WithMany("PrimaryPlayers")
                        .HasForeignKey("PrimaryPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArmadaEsports.Core.Models.Position", "SecondaryPosition")
                        .WithMany("SecondaryPlayers")
                        .HasForeignKey("SecondaryPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArmadaEsports.Core.Models.Position", "TertiaryPosition")
                        .WithMany("TertiaryPlayers")
                        .HasForeignKey("TertiaryPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrimaryPosition");

                    b.Navigation("SecondaryPosition");

                    b.Navigation("TertiaryPosition");
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.PlayerAttributeScore", b =>
                {
                    b.HasOne("ArmadaEsports.Core.Models.PlayerAttributeSnapshot", "Snapshot")
                        .WithMany("Scores")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.PlayerAttributeSnapshot", b =>
                {
                    b.HasOne("ArmadaEsports.Core.Models.Player", "Player")
                        .WithMany("AttributeSnapshots")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.AiMatchParseJob", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.Competition", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.Match", b =>
                {
                    b.Navigation("ParseJobs");

                    b.Navigation("PerformanceStats");
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.Player", b =>
                {
                    b.Navigation("AttributeSnapshots");

                    b.Navigation("PerformanceStats");
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.PlayerAttributeSnapshot", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("ArmadaEsports.Core.Models.Position", b =>
                {
                    b.Navigation("PrimaryPlayers");

                    b.Navigation("SecondaryPlayers");

                    b.Navigation("TertiaryPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
